# Generated by Django 3.2.20 on 2023-08-05 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('document', models.FileField(blank=True, null=True, upload_to='applications/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'application',
            },
        ),
        migrations.RemoveField(
            model_name='newfile',
            name='new_id',
        ),
        migrations.RemoveField(
            model_name='eventfile',
            name='file',
        ),
        migrations.AddField(
            model_name='eventfile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.DeleteModel(
            name='New',
        ),
        migrations.DeleteModel(
            name='NewFile',
        ),
    ]
