# Generated by Django 4.2.4 on 2023-12-16 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteManager', '0005_administration_course_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='MastersCostTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('units', models.CharField(max_length=200)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('NON_RESIDENTIAL', 'NON_RESIDENTIAL'), ('RESIDENTIAL', 'RESIDENTIAL')], default='RESIDENTIAL', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PhdCostTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteManager.course')),
            ],
        ),
    ]
