# Generated by Django 4.2.4 on 2023-12-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteManager', '0006_masterscosttable_phdcosttable'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportantInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission', models.TextField()),
                ('vision', models.TextField()),
                ('message_from_president', models.TextField()),
                ('historical_background', models.TextField()),
            ],
        ),
    ]
